// <auto-generated />
using System;
using JobOfferMatcher.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobOfferMatcher.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701181810_AffinityMetric")]
    partial class AffinityMetric
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationCommunication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("application_communication", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stored_file_name");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("application_document", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationInterview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Interviewer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("interviewer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("ScheduledAt");

                    b.ToTable("application_interview", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("application_note", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("OfferId", "CompletedAt");

                    b.ToTable("application_task", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.JobApplication", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrentStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_stage_id");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OfferId");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("Status");

                    b.ToTable("application", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.PipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.ToTable("pipeline_stage", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Cv.CandidateCv", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EnrichmentInputHash")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("enrichment_input_hash");

                    b.Property<DateTimeOffset?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsReadable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readable");

                    b.Property<string>("Profile")
                        .HasColumnType("jsonb")
                        .HasColumnName("profile");

                    b.Property<int>("ProfileAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("profile_attempts");

                    b.Property<DateTimeOffset?>("ProfileProducedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_produced_at");

                    b.Property<string>("ProfileState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("profile_state");

                    b.HasKey("Id");

                    b.ToTable("candidate_cv", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Enrichment.OfferAffinity", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("InputsHash")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("inputs_hash");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ProducedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("produced_at");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<string>("Resembles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resembles");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("OfferId");

                    b.HasIndex("State");

                    b.ToTable("offer_affinity", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Enrichment.OfferEnrichment", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("InputsHash")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("inputs_hash");

                    b.Property<string>("KeySkills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_skills");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ProducedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("produced_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("OfferId");

                    b.HasIndex("State");

                    b.ToTable("offer_enrichment", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Enrichment.OfferFit", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("InputsHash")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("inputs_hash");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Matched")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("matched");

                    b.Property<string>("Missing")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing");

                    b.Property<DateTimeOffset?>("ProducedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("produced_at");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("OfferId");

                    b.HasIndex("State");

                    b.ToTable("offer_fit", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("application_note");

                    b.Property<bool>("Applied")
                        .HasColumnType("boolean")
                        .HasColumnName("applied");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("availability");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("canonical_url");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<DateTimeOffset?>("DisappearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disappeared_at");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("employment_type");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("FirstSuggestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_suggested_at");

                    b.Property<bool>("HasUnseenUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("has_unseen_update");

                    b.Property<DateTimeOffset?>("LastPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_published_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("NiceToHaveSkills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nice_skills");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_skills");

                    b.Property<Guid?>("RoleGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_group_id");

                    b.Property<string>("SalaryBands")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("salary_bands");

                    b.Property<string>("Seniority")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("seniority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_status");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("work_mode");

                    b.HasKey("Id");

                    b.HasIndex("Applied");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("UserStatus");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("offer_event", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_run_id");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("ScanRunId");

                    b.ToTable("offer_observation", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("change_tier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("offer_version", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.RoleGroups.RoleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("MemberOfferIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("member_offer_ids");

                    b.Property<string>("UserOverride")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_override");

                    b.HasKey("Id");

                    b.ToTable("role_group", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Scans.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IncompleteReason")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("incomplete_reason");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_ids");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger");

                    b.Property<DateTimeOffset?>("WindowUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_utc");

                    b.HasKey("Id");

                    b.HasIndex("WindowUtc", "Trigger")
                        .IsUnique();

                    b.ToTable("scan_run", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Scheduling.ScheduleConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cron");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastRunUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_utc");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id");

                    b.ToTable("schedule_config", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Settings.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Enrichment")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("enrichment");

                    b.Property<string>("Normalization")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("salary_norm");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_prefs");

                    b.Property<string>("Weights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scoring_weights");

                    b.HasKey("Id");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Sources.JobSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_login");

                    b.Property<string>("Search")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("search_criteria");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("job_source", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.TailoredCvs.TailoredCv", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmphasisedSkills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("emphasised_skills");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("GenerationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("generation_version");

                    b.Property<string>("HtmlFileName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("html_file_name");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("PdfFileName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("pdf_file_name");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<Guid>("SourceCvId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_cv_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("OfferId");

                    b.HasIndex("State");

                    b.ToTable("tailored_cv", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationCommunication", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Applications.JobApplication", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationDocument", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Applications.JobApplication", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationInterview", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Applications.JobApplication", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationNote", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Applications.JobApplication", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.ApplicationTask", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Applications.JobApplication", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Applications.JobApplication", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Applications.PipelineStage", null)
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithOne()
                        .HasForeignKey("JobOfferMatcher.Domain.Applications.JobApplication", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Enrichment.OfferAffinity", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithOne()
                        .HasForeignKey("JobOfferMatcher.Domain.Enrichment.OfferAffinity", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Enrichment.OfferEnrichment", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithOne()
                        .HasForeignKey("JobOfferMatcher.Domain.Enrichment.OfferEnrichment", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Enrichment.OfferFit", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithOne()
                        .HasForeignKey("JobOfferMatcher.Domain.Enrichment.OfferFit", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.Offer", b =>
                {
                    b.OwnsOne("JobOfferMatcher.Domain.Offers.ExternalRef", "ExternalRef", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("identity_kind");

                            b1.Property<string>("NativeKey")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("native_key");

                            b1.Property<Guid>("SourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_id");

                            b1.HasKey("OfferId");

                            b1.HasIndex("SourceId", "NativeKey")
                                .IsUnique();

                            b1.ToTable("offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("JobOfferMatcher.Domain.Offers.ContentFingerprint", "CurrentFingerprint", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("fingerprint_algo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("current_fingerprint");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("fingerprint_version");

                            b1.HasKey("OfferId");

                            b1.ToTable("offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.Navigation("CurrentFingerprint")
                        .IsRequired();

                    b.Navigation("ExternalRef")
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferEvent", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferObservation", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobOfferMatcher.Domain.Offers.ContentFingerprint", "Fingerprint", b1 =>
                        {
                            b1.Property<Guid>("OfferObservationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("fingerprint_algo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("fingerprint");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("fingerprint_version");

                            b1.HasKey("OfferObservationId");

                            b1.ToTable("offer_observation");

                            b1.WithOwner()
                                .HasForeignKey("OfferObservationId");
                        });

                    b.Navigation("Fingerprint")
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferVersion", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobOfferMatcher.Domain.Offers.ContentFingerprint", "Fingerprint", b1 =>
                        {
                            b1.Property<Guid>("OfferVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("fingerprint_algo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("fingerprint");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("fingerprint_version");

                            b1.HasKey("OfferVersionId");

                            b1.ToTable("offer_version");

                            b1.WithOwner()
                                .HasForeignKey("OfferVersionId");
                        });

                    b.Navigation("Fingerprint")
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Scans.ScanRun", b =>
                {
                    b.OwnsOne("JobOfferMatcher.Domain.Scans.ScanCounts", "Counts", b1 =>
                        {
                            b1.Property<Guid>("ScanRunId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Collected")
                                .HasColumnType("integer")
                                .HasColumnName("count_collected");

                            b1.Property<int>("Failed")
                                .HasColumnType("integer")
                                .HasColumnName("count_failed");

                            b1.Property<int>("New")
                                .HasColumnType("integer")
                                .HasColumnName("count_new");

                            b1.Property<int>("Unavailable")
                                .HasColumnType("integer")
                                .HasColumnName("count_unavailable");

                            b1.Property<int>("Updated")
                                .HasColumnType("integer")
                                .HasColumnName("count_updated");

                            b1.HasKey("ScanRunId");

                            b1.ToTable("scan_run");

                            b1.WithOwner()
                                .HasForeignKey("ScanRunId");
                        });

                    b.Navigation("Counts")
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.TailoredCvs.TailoredCv", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithOne()
                        .HasForeignKey("JobOfferMatcher.Domain.TailoredCvs.TailoredCv", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
