// <auto-generated />
using System;
using JobOfferMatcher.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobOfferMatcher.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628182153_RoleGroups")]
    partial class RoleGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobOfferMatcher.Domain.Cv.CandidateCv", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DerivedProfile")
                        .HasColumnType("jsonb")
                        .HasColumnName("derived_profile");

                    b.Property<DateTimeOffset?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsReadable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readable");

                    b.HasKey("Id");

                    b.ToTable("candidate_cv", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("availability");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("canonical_url");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<DateTimeOffset?>("DisappearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disappeared_at");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("employment_type");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("FirstSuggestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_suggested_at");

                    b.Property<bool>("HasUnseenUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("has_unseen_update");

                    b.Property<DateTimeOffset?>("LastPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_published_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("NiceToHaveSkills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nice_skills");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_skills");

                    b.Property<Guid?>("RoleGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_group_id");

                    b.Property<string>("SalaryBands")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("salary_bands");

                    b.Property<string>("Seniority")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("seniority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_status");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("work_mode");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("UserStatus");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("offer_event", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_run_id");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("ScanRunId");

                    b.ToTable("offer_observation", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("change_tier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("offer_version", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.RoleGroups.RoleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("MemberOfferIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("member_offer_ids");

                    b.Property<string>("UserOverride")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_override");

                    b.HasKey("Id");

                    b.ToTable("role_group", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Scans.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IncompleteReason")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("incomplete_reason");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<string>("SourceIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_ids");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger");

                    b.Property<DateTimeOffset?>("WindowUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_utc");

                    b.HasKey("Id");

                    b.HasIndex("WindowUtc", "Trigger")
                        .IsUnique();

                    b.ToTable("scan_run", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Scheduling.ScheduleConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cron");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastRunUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_utc");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id");

                    b.ToTable("schedule_config", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Settings.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Normalization")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("salary_norm");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_prefs");

                    b.Property<string>("Weights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scoring_weights");

                    b.HasKey("Id");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Sources.JobSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_login");

                    b.Property<string>("Search")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("search_criteria");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("job_source", (string)null);
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.Offer", b =>
                {
                    b.OwnsOne("JobOfferMatcher.Domain.Offers.ExternalRef", "ExternalRef", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("identity_kind");

                            b1.Property<string>("NativeKey")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("native_key");

                            b1.Property<Guid>("SourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_id");

                            b1.HasKey("OfferId");

                            b1.HasIndex("SourceId", "NativeKey")
                                .IsUnique();

                            b1.ToTable("offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("JobOfferMatcher.Domain.Offers.ContentFingerprint", "CurrentFingerprint", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("fingerprint_algo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("current_fingerprint");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("fingerprint_version");

                            b1.HasKey("OfferId");

                            b1.ToTable("offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.Navigation("CurrentFingerprint")
                        .IsRequired();

                    b.Navigation("ExternalRef")
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferEvent", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferObservation", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobOfferMatcher.Domain.Offers.ContentFingerprint", "Fingerprint", b1 =>
                        {
                            b1.Property<Guid>("OfferObservationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("fingerprint_algo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("fingerprint");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("fingerprint_version");

                            b1.HasKey("OfferObservationId");

                            b1.ToTable("offer_observation");

                            b1.WithOwner()
                                .HasForeignKey("OfferObservationId");
                        });

                    b.Navigation("Fingerprint")
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Offers.OfferVersion", b =>
                {
                    b.HasOne("JobOfferMatcher.Domain.Offers.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobOfferMatcher.Domain.Offers.ContentFingerprint", "Fingerprint", b1 =>
                        {
                            b1.Property<Guid>("OfferVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("fingerprint_algo");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("fingerprint");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("fingerprint_version");

                            b1.HasKey("OfferVersionId");

                            b1.ToTable("offer_version");

                            b1.WithOwner()
                                .HasForeignKey("OfferVersionId");
                        });

                    b.Navigation("Fingerprint")
                        .IsRequired();
                });

            modelBuilder.Entity("JobOfferMatcher.Domain.Scans.ScanRun", b =>
                {
                    b.OwnsOne("JobOfferMatcher.Domain.Scans.ScanCounts", "Counts", b1 =>
                        {
                            b1.Property<Guid>("ScanRunId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Collected")
                                .HasColumnType("integer")
                                .HasColumnName("count_collected");

                            b1.Property<int>("Failed")
                                .HasColumnType("integer")
                                .HasColumnName("count_failed");

                            b1.Property<int>("New")
                                .HasColumnType("integer")
                                .HasColumnName("count_new");

                            b1.Property<int>("Unavailable")
                                .HasColumnType("integer")
                                .HasColumnName("count_unavailable");

                            b1.Property<int>("Updated")
                                .HasColumnType("integer")
                                .HasColumnName("count_updated");

                            b1.HasKey("ScanRunId");

                            b1.ToTable("scan_run");

                            b1.WithOwner()
                                .HasForeignKey("ScanRunId");
                        });

                    b.Navigation("Counts")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
