import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import type { TailoredCvDto } from '../../api/types.ts'
import {
  deleteTailored,
  downloadTailoredPdf,
  listTailored,
  previewUrl,
} from '../../api/tailoredCv.ts'
import { ApiError } from '../../api/client.ts'
import { TailorCvModal } from '../../components/TailorCvModal/TailorCvModal.tsx'
import { enrichmentStatusClass } from '../../theme/index.ts'
import { formatDateUtc } from '../../lib/format.ts'
import './TailoredCvsPage.css'

/**
 * The dedicated page listing every tailored CV (US4). Each row reaches its offer (opening the
 * offer-scoped modal to view/edit-prompt/regenerate) and offers view (preview) / download / remove.
 * A tailored CV persists here even after its offer is delisted (FR-018).
 */
export function TailoredCvsPage() {
  const [items, setItems] = useState<TailoredCvDto[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [modalFor, setModalFor] = useState<TailoredCvDto | null>(null)
  const [downloadingId, setDownloadingId] = useState<string | null>(null)

  const reload = useCallback(async (signal?: AbortSignal) => {
    try {
      const { data } = await listTailored(signal)
      setItems(data)
      setError(null)
    } catch (e) {
      if (e instanceof DOMException && e.name === 'AbortError') return
      setError(e instanceof ApiError ? e.message : 'Failed to load tailored CVs.')
    } finally {
      if (!signal?.aborted) setLoading(false)
    }
  }, [])

  useEffect(() => {
    const controller = new AbortController()
    void reload(controller.signal)
    return () => controller.abort()
  }, [reload])

  async function handleDownload(offerId: string) {
    setDownloadingId(offerId)
    try {
      await downloadTailoredPdf(offerId)
    } catch (e) {
      setError(e instanceof ApiError ? e.message : 'Download failed.')
    } finally {
      setDownloadingId(null)
    }
  }

  async function handleRemove(offerId: string) {
    try {
      await deleteTailored(offerId)
      await reload()
    } catch (e) {
      setError(e instanceof ApiError ? e.message : 'Failed to remove the tailored CV.')
    }
  }

  return (
    <section className="tailored-cvs-page">
      <h1 className="page-title">Tailored CVs</h1>
      <p className="page-subtitle">
        CVs you have tailored to a specific offer. Generated by the local /tailor-cv worker.
      </p>

      {error && (
        <div className="cv-msg cv-msg--error" role="alert">
          {error}
        </div>
      )}

      {loading && (
        <div className="state-block">
          <span className="spinner" aria-label="Loading" /> Loading tailored CVs…
        </div>
      )}

      {!loading && items.length === 0 && (
        <div className="state-block" data-testid="empty-state">
          No tailored CVs yet — open an offer and choose <strong>Tailor CV</strong>.
        </div>
      )}

      {!loading && items.length > 0 && (
        <ul className="tailored-cvs-list">
          {items.map((item) => (
            <li key={item.offerId} className="card tailored-cv-row" data-testid="tailored-cv-row">
              <div className="tailored-cv-row__main">
                <button
                  type="button"
                  className="tailored-cv-row__title"
                  onClick={() => setModalFor(item)}
                  data-testid="tailored-cv-open"
                >
                  {item.offerTitle}
                </button>
                <div className="tailored-cv-row__company muted">{item.company}</div>
                <div className="tailored-cv-row__meta">
                  <span className={enrichmentStatusClass(item.state)}>
                    {item.state === 'produced'
                      ? 'Produced'
                      : item.state === 'failed'
                        ? 'Failed'
                        : 'Pending'}
                  </span>
                  {item.generatedAt && (
                    <span className="muted text-sm">
                      Generated {formatDateUtc(item.generatedAt)}
                    </span>
                  )}
                </div>
              </div>
              <div className="tailored-cv-row__actions">
                <Link className="btn btn--ghost btn--sm" to={`/?offerId=${item.offerId}`}>
                  View offer
                </Link>
                {item.state === 'produced' && (
                  <a
                    className="btn btn--ghost btn--sm"
                    href={previewUrl(item.offerId, item.generationVersion)}
                    target="_blank"
                    rel="noreferrer noopener"
                  >
                    View
                  </a>
                )}
                <button
                  type="button"
                  className="btn btn--ghost btn--sm"
                  onClick={() => setModalFor(item)}
                >
                  Regenerate
                </button>
                {item.hasPdf && (
                  <button
                    type="button"
                    className="btn btn--ghost btn--sm"
                    onClick={() => handleDownload(item.offerId)}
                    disabled={downloadingId === item.offerId}
                  >
                    {downloadingId === item.offerId ? 'Downloading…' : 'Download'}
                  </button>
                )}
                <button
                  type="button"
                  className="btn btn--ghost btn--sm"
                  onClick={() => handleRemove(item.offerId)}
                  aria-label={`Remove tailored CV for ${item.offerTitle}`}
                >
                  Remove
                </button>
              </div>
            </li>
          ))}
        </ul>
      )}

      {modalFor && (
        <TailorCvModal
          offerId={modalFor.offerId}
          offerTitle={modalFor.offerTitle}
          onClose={() => {
            setModalFor(null)
            void reload()
          }}
          onChanged={reload}
        />
      )}
    </section>
  )
}
